package com.xiaoxin.sleep.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xiaoxin.sleep.model.db.AppInfoBean;
import com.xiaoxin.sleep.model.db.UserAppInfoBean;

import com.xiaoxin.sleep.greendao.AppInfoBeanDao;
import com.xiaoxin.sleep.greendao.UserAppInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoBeanDaoConfig;
    private final DaoConfig userAppInfoBeanDaoConfig;

    private final AppInfoBeanDao appInfoBeanDao;
    private final UserAppInfoBeanDao userAppInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoBeanDaoConfig = daoConfigMap.get(AppInfoBeanDao.class).clone();
        appInfoBeanDaoConfig.initIdentityScope(type);

        userAppInfoBeanDaoConfig = daoConfigMap.get(UserAppInfoBeanDao.class).clone();
        userAppInfoBeanDaoConfig.initIdentityScope(type);

        appInfoBeanDao = new AppInfoBeanDao(appInfoBeanDaoConfig, this);
        userAppInfoBeanDao = new UserAppInfoBeanDao(userAppInfoBeanDaoConfig, this);

        registerDao(AppInfoBean.class, appInfoBeanDao);
        registerDao(UserAppInfoBean.class, userAppInfoBeanDao);
    }
    
    public void clear() {
        appInfoBeanDaoConfig.clearIdentityScope();
        userAppInfoBeanDaoConfig.clearIdentityScope();
    }

    public AppInfoBeanDao getAppInfoBeanDao() {
        return appInfoBeanDao;
    }

    public UserAppInfoBeanDao getUserAppInfoBeanDao() {
        return userAppInfoBeanDao;
    }

}
