package com.xiaoxin.sleep.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xiaoxin.sleep.model.db.UserAppInfoBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_APP_INFO_BEAN".
*/
public class UserAppInfoBeanDao extends AbstractDao<UserAppInfoBean, Long> {

    public static final String TABLENAME = "USER_APP_INFO_BEAN";

    /**
     * Properties of entity UserAppInfoBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AppName = new Property(1, String.class, "appName", false, "APP_NAME");
        public final static Property PackageName = new Property(2, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property File_path = new Property(3, String.class, "file_path", false, "FILE_PATH");
        public final static Property Open_num = new Property(4, int.class, "open_num", false, "OPEN_NUM");
    }


    public UserAppInfoBeanDao(DaoConfig config) {
        super(config);
    }
    
    public UserAppInfoBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_APP_INFO_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"APP_NAME\" TEXT," + // 1: appName
                "\"PACKAGE_NAME\" TEXT," + // 2: packageName
                "\"FILE_PATH\" TEXT," + // 3: file_path
                "\"OPEN_NUM\" INTEGER NOT NULL );"); // 4: open_num
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_APP_INFO_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserAppInfoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String appName = entity.getAppName();
        if (appName != null) {
            stmt.bindString(2, appName);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(3, packageName);
        }
 
        String file_path = entity.getFile_path();
        if (file_path != null) {
            stmt.bindString(4, file_path);
        }
        stmt.bindLong(5, entity.getOpen_num());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserAppInfoBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String appName = entity.getAppName();
        if (appName != null) {
            stmt.bindString(2, appName);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(3, packageName);
        }
 
        String file_path = entity.getFile_path();
        if (file_path != null) {
            stmt.bindString(4, file_path);
        }
        stmt.bindLong(5, entity.getOpen_num());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserAppInfoBean readEntity(Cursor cursor, int offset) {
        UserAppInfoBean entity = new UserAppInfoBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // appName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // packageName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // file_path
            cursor.getInt(offset + 4) // open_num
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserAppInfoBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAppName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPackageName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFile_path(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOpen_num(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserAppInfoBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserAppInfoBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserAppInfoBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
